### ISSUE TITLE
Broken `yarn mintERC20` inside `sygma-sdk-erc20-react-example`

### ISSUE THREAD

**Issue by BeroBurny** [sygmaprotocol/sygma-sdk#150]
```
/sygma-sdk/examples/erc20-react-example$ yarn mintERC20
yarn run v1.22.19
$ ts-node ./src/scripts/mint.ts
wallet address:  0x5C1F5961696BaD2e73f73417f07EF55C62a2dC5b
wallet private key:  0xcc2c32b154490f09f70c1c8d4b997238448d649e0777495863db231c4ced3616
/home/bero/WebstormProjects/sygma-sdk/examples/erc20-react-example/node_modules/@ethersproject/wallet/node_modules/@ethersproject/logger/src.ts/index.ts:269
        const error: any = new Error(message);
                           ^
<ref *1> Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"id\":52,\"jsonrpc\":\"2.0\",\"error\":{\"message\":\"VM Exception while processing transaction: revert\",\"code\":-32000,\"data\":{\"stack\":\"o: VM Exception while processing transaction: revert\\n    at Function.o.fromResults (/app/ganache-core.docker.cli.js:4:297036)\\n    at e.exports (/app/ganache-core.docker.cli.js:55:2302856)\",\"name\":\"o\"}}}","error":{"code":-32000,"data":{"stack":"o: VM Exception while processing transaction: revert\n    at Function.o.fromResults (/app/ganache-core.docker.cli.js:4:297036)\n    at e.exports (/app/ganache-core.docker.cli.js:55:2302856)","name":"o"}},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"gasPrice\":\"0x4a817c800\",\"from\":\"0x5c1f5961696bad2e73f73417f07ef55c62a2dc5b\",\"to\":\"0x1ccb4231f2ff299e1e049de76f0a1d2b415c563a\",\"data\":\"0x40c10f190000000000000000000000005c1f5961696bad2e73f73417f07ef55c62a2dc5b0000000000000000000000000000000000000000000000055de6a779bbac0000\"}],\"id\":52,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://localhost:8547"}, tx={"data":"0x40c10f190000000000000000000000005c1f5961696bad2e73f73417f07ef55c62a2dc5b0000000000000000000000000000000000000000000000055de6a779bbac0000","to":{},"from":"0x5C1F5961696BaD2e73f73417f07EF55C62a2dC5b","gasPrice":{"type":"BigNumber","hex":"0x04a817c800"},"type":0,"nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.7.0)
    at Logger.makeError (/home/bero/WebstormProjects/sygma-sdk/examples/erc20-react-example/node_modules/@ethersproject/wallet/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/home/bero/WebstormProjects/sygma-sdk/examples/erc20-react-example/node_modules/@ethersproject/wallet/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at /home/bero/WebstormProjects/sygma-sdk/examples/erc20-react-example/node_modules/@ethersproject/wallet/node_modules/@ethersproject/abstract-signer/src.ts/index.ts:301:31
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 6) {
  reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  error: Error: processing response error (body="{\"id\":52,\"jsonrpc\":\"2.0\",\"error\":{\"message\":\"VM Exception while processing transaction: revert\",\"code\":-32000,\"data\":{\"stack\":\"o: VM Exception while processing transaction: revert\\n    at Function.o.fromResults (/app/ganache-core.docker.cli.js:4:297036)\\n    at e.exports (/app/ganache-core.docker.cli.js:55:2302856)\",\"name\":\"o\"}}}", error={"code":-32000,"data":{"stack":"o: VM Exception while processing transaction: revert\n    at Function.o.fromResults (/app/ganache-core.docker.cli.js:4:297036)\n    at e.exports (/app/ganache-core.docker.cli.js:55:2302856)","name":"o"}}, requestBody="{\"method\":\"eth_estimateGas\",\"params\":[{\"gasPrice\":\"0x4a817c800\",\"from\":\"0x5c1f5961696bad2e73f73417f07ef55c62a2dc5b\",\"to\":\"0x1ccb4231f2ff299e1e049de76f0a1d2b415c563a\",\"data\":\"0x40c10f190000000000000000000000005c1f5961696bad2e73f73417f07ef55c62a2dc5b0000000000000000000000000000000000000000000000055de6a779bbac0000\"}],\"id\":52,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://localhost:8547", code=SERVER_ERROR, version=web/5.7.0)
      at Logger.makeError (/home/bero/WebstormProjects/sygma-sdk/examples/erc20-react-example/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
      at Logger.throwError (/home/bero/WebstormProjects/sygma-sdk/examples/erc20-react-example/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
      at /home/bero/WebstormProjects/sygma-sdk/examples/erc20-react-example/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/src.ts/index.ts:335:28
      at step (/home/bero/WebstormProjects/sygma-sdk/examples/erc20-react-example/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (/home/bero/WebstormProjects/sygma-sdk/examples/erc20-react-example/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (/home/bero/WebstormProjects/sygma-sdk/examples/erc20-react-example/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:95:5) {
    reason: 'processing response error',
    code: 'SERVER_ERROR',
    body: '{"id":52,"jsonrpc":"2.0","error":{"message":"VM Exception while processing transaction: revert","code":-32000,"data":{"stack":"o: VM Exception while processing transaction: revert\\n    at Function.o.fromResults (/app/ganache-core.docker.cli.js:4:297036)\\n    at e.exports (/app/ganache-core.docker.cli.js:55:2302856)","name":"o"}}}',
    error: Error: VM Exception while processing transaction: revert
        at getResult (/home/bero/WebstormProjects/sygma-sdk/examples/erc20-react-example/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:125:28)
        at processJsonFunc (/home/bero/WebstormProjects/sygma-sdk/examples/erc20-react-example/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/src.ts/index.ts:377:22)
        at /home/bero/WebstormProjects/sygma-sdk/examples/erc20-react-example/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/src.ts/index.ts:314:42
        at step (/home/bero/WebstormProjects/sygma-sdk/examples/erc20-react-example/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:33:23)
        at Object.next (/home/bero/WebstormProjects/sygma-sdk/examples/erc20-react-example/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:14:53)
        at fulfilled (/home/bero/WebstormProjects/sygma-sdk/examples/erc20-react-example/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:5:58)
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      code: -32000,
      data: [Object]
    },
    requestBody: '{"method":"eth_estimateGas","params":[{"gasPrice":"0x4a817c800","from":"0x5c1f5961696bad2e73f73417f07ef55c62a2dc5b","to":"0x1ccb4231f2ff299e1e049de76f0a1d2b415c563a","data":"0x40c10f190000000000000000000000005c1f5961696bad2e73f73417f07ef55c62a2dc5b0000000000000000000000000000000000000000000000055de6a779bbac0000"}],"id":52,"jsonrpc":"2.0"}',
    requestMethod: 'POST',
    url: 'http://localhost:8547'
  },
  tx: {
    data: '0x40c10f190000000000000000000000005c1f5961696bad2e73f73417f07ef55c62a2dc5b0000000000000000000000000000000000000000000000055de6a779bbac0000',
    to: Promise { '0x1CcB4231f2ff299E1E049De76F0a1D2B415C563A' },
    from: '0x5C1F5961696BaD2e73f73417f07EF55C62a2dC5b',
    gasPrice: BigNumber { _hex: '0x04a817c800', _isBigNumber: true },
    type: 0,
    nonce: Promise { 39 },
    gasLimit: Promise { <rejected> [Circular *1] },
    chainId: Promise { 1338 }
  }
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by enemycnt** [comment]
Local setup now comes with pre-mined erc20 test tokens for account `0x5C1F5961696BaD2e73f73417f07EF55C62a2dC5b`
